rally:
  jwt:
    secret: ${JWT_SECRET:/Wepykoli0z1033egoGDdLrm3eohJiOJUxT5L/RxgV0=}

deal:
  service:
    url: ${DEAL_SERVICE_URL:http://localhost:8085}
    mock:
      has-active-deal: ${DEAL_SERVICE_MOCK_HAS_ACTIVE_DEAL:false}

app:
  storage:
    root: ${STORAGE_ROOT:./uploads}

spring:
  application:
    name: rally-catalog

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:catalog_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: catalog-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8083
