-- =====================================================================
-- Seed catalog with curated demo data from DummyJSON
-- Source: https://dummyjson.com/products (free demo API, MIT-style dataset)
-- Deterministic ids: category = cat-seed-<slug>, product = dummy-<id>
-- All products APPROVED so they appear in buyer browse/search
-- =====================================================================
INSERT INTO categories (id, name, description, created_at) VALUES
    ('cat-seed-electronics', 'Electronics', 'Laptops, devices and mobile accessories', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (id, name, description, created_at) VALUES
    ('cat-seed-watches', 'Watches', 'Premium watches and timepieces', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (id, name, description, created_at) VALUES
    ('cat-seed-shoes', 'Shoes', 'Footwear for every occasion', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (id, name, description, created_at) VALUES
    ('cat-seed-home', 'Home & Furniture', 'Furniture and decor for your home', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (id, name, description, created_at) VALUES
    ('cat-seed-beauty', 'Beauty & Fragrance', 'Skincare, makeup and fragrances', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO categories (id, name, description, created_at) VALUES
    ('cat-seed-menswear', 'Menswear', 'Shirts and men''s clothing', now()) ON CONFLICT (name) DO NOTHING;

INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0078', 'user-seed-0001', 'Apple MacBook Pro 14 Inch Space Grey', 'The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple''s M1 Pro chip for exceptional performance and a stunning Retina display.', (SELECT id FROM categories WHERE name = 'Electronics'), 1999.99, 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0079', 'user-seed-0001', 'Asus Zenbook Pro Dual Screen Laptop', 'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.', (SELECT id FROM categories WHERE name = 'Electronics'), 1799.99, 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0080', 'user-seed-0001', 'Huawei Matebook X Pro', 'The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.', (SELECT id FROM categories WHERE name = 'Electronics'), 1399.99, 'https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0081', 'user-seed-0001', 'Lenovo Yoga 920', 'The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.', (SELECT id FROM categories WHERE name = 'Electronics'), 1099.99, 'https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp', 'APPROVED', now(), now());

INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0093', 'user-seed-0001', 'Brown Leather Belt Watch', 'The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.', (SELECT id FROM categories WHERE name = 'Watches'), 89.99, 'https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0094', 'user-seed-0001', 'Longines Master Collection', 'The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it''s a symbol of luxury and sophistication.', (SELECT id FROM categories WHERE name = 'Watches'), 1499.99, 'https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0095', 'user-seed-0001', 'Rolex Cellini Date Black Dial', 'The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex''s heritage.', (SELECT id FROM categories WHERE name = 'Watches'), 8999.99, 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0096', 'user-seed-0001', 'Rolex Cellini Moonphase', 'The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex''s commitment to precision and elegance.', (SELECT id FROM categories WHERE name = 'Watches'), 12999.99, 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp', 'APPROVED', now(), now());

INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0088', 'user-seed-0001', 'Nike Air Jordan 1 Red And Black', 'The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.', (SELECT id FROM categories WHERE name = 'Shoes'), 149.99, 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0089', 'user-seed-0001', 'Nike Baseball Cleats', 'Nike Baseball Cleats are designed for maximum traction and performance on the baseball field. They provide stability and support for players during games and practices.', (SELECT id FROM categories WHERE name = 'Shoes'), 79.99, 'https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0090', 'user-seed-0001', 'Puma Future Rider Trainers', 'The Puma Future Rider Trainers offer a blend of retro style and modern comfort. Perfect for casual wear, these trainers provide a fashionable and comfortable option for everyday use.', (SELECT id FROM categories WHERE name = 'Shoes'), 89.99, 'https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0091', 'user-seed-0001', 'Sports Sneakers Off White & Red', 'The Sports Sneakers in Off White and Red combine style and functionality, making them a fashionable choice for sports enthusiasts. The red and off-white color combination adds a bold and energetic touch.', (SELECT id FROM categories WHERE name = 'Shoes'), 119.99, 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp', 'APPROVED', now(), now());

INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0011', 'user-seed-0001', 'Annibale Colombo Bed', 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 1899.99, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0012', 'user-seed-0001', 'Annibale Colombo Sofa', 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 2499.99, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0013', 'user-seed-0001', 'Bedside Table African Cherry', 'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 299.99, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0014', 'user-seed-0001', 'Knoll Saarinen Executive Conference Chair', 'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 499.99, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp', 'APPROVED', now(), now());

INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0001', 'user-seed-0001', 'Essence Mascara Lash Princess', 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.', (SELECT id FROM categories WHERE name = 'Beauty & Fragrance'), 9.99, 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0002', 'user-seed-0001', 'Eyeshadow Palette with Mirror', 'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.', (SELECT id FROM categories WHERE name = 'Beauty & Fragrance'), 19.99, 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0003', 'user-seed-0001', 'Powder Canister', 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.', (SELECT id FROM categories WHERE name = 'Beauty & Fragrance'), 14.99, 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0004', 'user-seed-0001', 'Red Lipstick', 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.', (SELECT id FROM categories WHERE name = 'Beauty & Fragrance'), 12.99, 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp', 'APPROVED', now(), now());

INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0083', 'user-seed-0001', 'Blue & Black Check Shirt', 'The Blue & Black Check Shirt is a stylish and comfortable men''s shirt featuring a classic check pattern. Made from high-quality fabric, it''s suitable for both casual and semi-formal occasions.', (SELECT id FROM categories WHERE name = 'Menswear'), 29.99, 'https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0084', 'user-seed-0001', 'Gigabyte Aorus Men Tshirt', 'The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it''s perfect for expressing your gaming style.', (SELECT id FROM categories WHERE name = 'Menswear'), 24.99, 'https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0085', 'user-seed-0001', 'Man Plaid Shirt', 'The Man Plaid Shirt is a timeless and versatile men''s shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.', (SELECT id FROM categories WHERE name = 'Menswear'), 34.99, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('dummy-0086', 'user-seed-0001', 'Man Short Sleeve Shirt', 'The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it''s perfect for a laid-back yet polished look.', (SELECT id FROM categories WHERE name = 'Menswear'), 19.99, 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp', 'APPROVED', now(), now());

