-- =====================================================================
-- Seed the products referenced by the demo group deals (shared mock deal
-- store in rally-ui). Ids are md5('dummy-<n>')::uuid::text so they match
-- the deterministic conversion applied by V3__convert_seed_ids_to_uuid.
-- The deal store links to these exact ids so the buyer deal view resolves
-- real catalog product data (image, title, description, category).
-- =====================================================================
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('2bf8a0ab-103d-f678-290b-bf4b1762fd01', 'user-seed-0001', 'Artisan Ceramic Brew Set', 'A handcrafted ceramic pour-over set — brewer, dripper and two mugs — for slow mornings and rich coffee.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 49.99, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDSGkOu2tweFMl4s3ixgYD5Q2-gIzYt3WNvn3sJKDRFXRhCgb_XCTPoGbMspTbBu3sISO2ldSINv62qtessJlzvwOglK_cdJiNJsopUA-MFNmmOxR57AqoqHNC-pbY_Arx8sh2pvE-gjDRzTGMYM4QYvbg4LdlJkLTNP5nwBUF2NaGhwaPQG2hzAOWFjS0VVFlYPl_f0UlCl6hKd690Hq0U6BTY9oK4tfBek9EJFhte6Oxl98cNUXhcKOVz9ANdO-4HyXH9G4y5CwE', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('fcf79a97-1202-28e3-7937-66b59b744a1a', 'user-seed-0001', 'Sonic Pro Wireless', 'Wireless over-ear headphones with active noise cancelling, 40h battery life and crisp studio sound.', (SELECT id FROM categories WHERE name = 'Electronics'), 199.0, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBwUCxSF-_QRIwIV2buXvV9w90sb7E4VDit2cGcMWMpQ-ntIOypgE1uOgxBWky-11Kyfj2626OfQ3RLftzl032QrFxFm5NQtgK-7jcbUKgsqIJtgFCx4QZrLH9vi3cxMjvpsqtySdpAYX-IygEzvJd4xweayGHNmgA9nCPmOiEubP7L2a4l3kTeqF9xB68WdR3CRAwDv_LS_VoVtoh7ajAgJDijm-rX_Hn0lSYv8Nl3-nX2fzit42S4STLWdi8935or6VJjIfTW-e4', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('419c9562-6d38-1da9-47b2-b59e8fb16a70', 'user-seed-0001', 'AquaSmart Hydration', 'A leak-proof smart water bottle that tracks your intake and glows to remind you to hydrate.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 30.0, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdum2tVVRwEgwEWwqrdWvCFaQ18f32GUkCr1O69zLXM6H1eCabBS_brs81RRYd54giYLj9iHwE45mweyusCcd8zdq6aMe2waSf8ThKpgAoKBAnL2RZnzobMoq05BpD0aBXK3o9Dow9ZrhBoSpwSY_3C0t47FnxP0icnOA9kLcTO7QYux1w7Du_7xSIEGCt_olhmbsSzJ1wp1kAakor2jpdjWT21RK_jo3-Fpphtg1v0bx_y-Nnsprn2Q7nk6ANAAAk16IJDzSca-Q', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('60930722-39b4-9b3a-3f08-07c0926e5450', 'user-seed-0001', 'EcoTech Tech Pouch', 'A recycled-ripstop tech organizer that keeps cables, chargers and earbuds tidy on the move.', (SELECT id FROM categories WHERE name = 'Electronics'), 25.0, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDSmxS5Ux__--cPa3idO0LDpBMCzclCXsfH9YZpuq_qCY68xq2e2a5Mz05VS-9EuHJUK6_JNKPatVi-ar2aj_bN1XgCOUsIggbsuEOxjd_rsbrt-qE4IHOxZffbAyrlWLH2jt9kKuHALmtsCh437hYj6uH1Bl4dEjxG_woOwSM10AfytRrBvS-uB6d2rHOZBohrs29-S8ydsNfot9BGb6EbNl_AJ2SPaxm1K9rogyNlU_qgvuGsHu_4mVXjVxTU1z_lUAXhS2aAEg', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('5a5352fb-86a2-ce81-d8ce-c746fb16a9c7', 'user-seed-0001', 'Summit Trail Backpack', 'A 28L daypack with a ventilated back panel, padded 15-inch laptop sleeve and weatherproof zips.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 70.0, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDt0vfHKyf-KWvrp3ab2lYy2T643Sjjl6sT_KcbSeqNzT-3k62dj5SQuaD4BjptmB35Zs9uSy5rdM1T9LN6iPeVW4xZYSrQjGctukrGc3-raf7dqF7unX_UN60G-LVJ1P7llFmGmXhLpV2ZBVHmShTFvWyMPpRkPEDNRxarGN2oKKcA3BFZaEqLh63N1gjaaCqBWn27oxodcDLG5koAADfFQZI4tpWq2bqll05fmsR1Nq_X81WrOOZ1wXqM1B8HCEw7MfpR8Gbmgo4', 'APPROVED', now(), now());
INSERT INTO products (id, seller_id, name, description, category_id, base_price, image_url, status, created_at, updated_at) VALUES
    ('52a9f1b9-ee61-ee54-eba2-2532c5d138ef', 'user-seed-0001', 'Lumen Desk Lamp', 'A minimal LED desk lamp with warm-to-cool dimming, a USB-C charging port and touch control.', (SELECT id FROM categories WHERE name = 'Home & Furniture'), 32.0, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgxNrJsmbVdEsMq9E2yT7qkWEDEhhtW1gAlQKbdD0W-FyPJK6rhVuRLNUh9IoxlximM6CpdwvZOyQ1MoQN2VGx5p-DMDTeKHbvQXUCNRZfsHK0jhwVysf-7Y-4TY3PoqcRbignibynp97Ye0XNL7SwYGZ-ZVlnDFm1WiFLebxwJASm6kEoR3G_INAwp-yITH8yMr6wQiaU_6I_HaMM7t5X2LWa2P_h2-K2XspnTlMP2x5YYN5x4Qs106T9lYaK8wbwqGZg8vDtXMA', 'APPROVED', now(), now());
